development:
  dialect: postgres
  datasource: postgresql://user:pass@localhost/echobase?sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: ${EB_DSN}
  dir: migrations
  table: migrations

