// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gamer_profile.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getStudent = `-- name: GetStudent :one
SELECT id, student_number, first_name, last_name, membership_tier,
       banned, notes, created_at, membership_expiry_date
FROM gamer_profile
WHERE student_number = $1
`

type GetStudentRow struct {
	ID                   uuid.NullUUID
	StudentNumber        string
	FirstName            string
	LastName             string
	MembershipTier       int32
	Banned               sql.NullBool
	Notes                sql.NullString
	CreatedAt            sql.NullTime
	MembershipExpiryDate sql.NullTime
}

func (q *Queries) GetStudent(ctx context.Context, studentNumber string) (GetStudentRow, error) {
	row := q.db.QueryRowContext(ctx, getStudent, studentNumber)
	var i GetStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.MembershipTier,
		&i.Banned,
		&i.Notes,
		&i.CreatedAt,
		&i.MembershipExpiryDate,
	)
	return i, err
}
