// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gamer_activity.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGamerActivity = `-- name: CreateGamerActivity :one
INSERT INTO gamer_activity (id, student_number, pc_number, game, started_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, student_number, pc_number, game, started_at, ended_at, exec_name
`

type CreateGamerActivityParams struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
}

type CreateGamerActivityRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
}

func (q *Queries) CreateGamerActivity(ctx context.Context, arg CreateGamerActivityParams) (CreateGamerActivityRow, error) {
	row := q.db.QueryRowContext(ctx, createGamerActivity,
		arg.ID,
		arg.StudentNumber,
		arg.PcNumber,
		arg.Game,
		arg.StartedAt,
	)
	var i CreateGamerActivityRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.PcNumber,
		&i.Game,
		&i.StartedAt,
		&i.EndedAt,
		&i.ExecName,
	)
	return i, err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT ga.id, ga.student_number, ga.pc_number, ga.game, ga.started_at, ga.ended_at, ga.exec_name,
       gp.first_name, gp.last_name
FROM gamer_activity ga
JOIN gamer_profile gp ON ga.student_number = gp.student_number
WHERE ga.ended_at IS NULL
`

type GetActiveSessionsRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
	FirstName     string
	LastName      string
}

func (q *Queries) GetActiveSessions(ctx context.Context) ([]GetActiveSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSessionsRow
	for rows.Next() {
		var i GetActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.PcNumber,
			&i.Game,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExecName,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamerActivity = `-- name: GetGamerActivity :many
SELECT id, student_number, pc_number, game, started_at, ended_at, exec_name
FROM gamer_activity
WHERE student_number = $1
ORDER BY started_at DESC
`

type GetGamerActivityRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
}

func (q *Queries) GetGamerActivity(ctx context.Context, studentNumber string) ([]GetGamerActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getGamerActivity, studentNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamerActivityRow
	for rows.Next() {
		var i GetGamerActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.PcNumber,
			&i.Game,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExecName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivities = `-- name: GetRecentActivities :many
SELECT ga.id, ga.student_number, ga.pc_number, ga.game, ga.started_at, ga.ended_at, ga.exec_name,
       gp.first_name, gp.last_name
FROM gamer_activity ga
JOIN gamer_profile gp ON ga.student_number = gp.student_number
ORDER BY ga.started_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetRecentActivitiesParams struct {
	Limit  int64
	Offset int64
}

type GetRecentActivitiesRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
	FirstName     string
	LastName      string
}

func (q *Queries) GetRecentActivities(ctx context.Context, arg GetRecentActivitiesParams) ([]GetRecentActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivitiesRow
	for rows.Next() {
		var i GetRecentActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.PcNumber,
			&i.Game,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExecName,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivitiesWithSearch = `-- name: GetRecentActivitiesWithSearch :many
SELECT ga.id, ga.student_number, ga.pc_number, ga.game, ga.started_at, ga.ended_at, ga.exec_name,
       gp.first_name, gp.last_name
FROM gamer_activity ga
JOIN gamer_profile gp ON ga.student_number = gp.student_number
WHERE ga.student_number::TEXT ILIKE '%' || $3 || '%'
   OR gp.first_name ILIKE '%' || $3 || '%'
   OR gp.last_name ILIKE '%' || $3 || '%'
   OR ga.game ILIKE '%' || $3 || '%'
   OR ga.exec_name ILIKE '%' || $3 || '%'
ORDER BY ga.started_at DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetRecentActivitiesWithSearchParams struct {
	Limit   int64
	Offset  int64
	Column3 sql.NullString
}

type GetRecentActivitiesWithSearchRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
	FirstName     string
	LastName      string
}

func (q *Queries) GetRecentActivitiesWithSearch(ctx context.Context, arg GetRecentActivitiesWithSearchParams) ([]GetRecentActivitiesWithSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivitiesWithSearch, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivitiesWithSearchRow
	for rows.Next() {
		var i GetRecentActivitiesWithSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.PcNumber,
			&i.Game,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExecName,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayActivitiesByStudent = `-- name: GetTodayActivitiesByStudent :many
SELECT ga.id, ga.student_number, ga.pc_number, ga.game, ga.started_at, ga.ended_at, ga.exec_name
FROM gamer_activity ga
JOIN gamer_profile gp ON ga.student_number = gp.student_number
WHERE ga.student_number = $1
AND gp.membership_tier = 1
AND DATE(ga.started_at AT TIME ZONE 'America/Los_Angeles') = DATE(NOW() AT TIME ZONE 'America/Los_Angeles')
`

type GetTodayActivitiesByStudentRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
}

func (q *Queries) GetTodayActivitiesByStudent(ctx context.Context, studentNumber string) ([]GetTodayActivitiesByStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodayActivitiesByStudent, studentNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodayActivitiesByStudentRow
	for rows.Next() {
		var i GetTodayActivitiesByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.PcNumber,
			&i.Game,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExecName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityEndTime = `-- name: UpdateActivityEndTime :one
UPDATE gamer_activity
SET ended_at = $1, exec_name = $2
WHERE student_number = $3
AND pc_number = $4
AND ended_at IS NULL
RETURNING id, student_number, pc_number, game, started_at, ended_at, exec_name
`

type UpdateActivityEndTimeParams struct {
	EndedAt       sql.NullTime
	ExecName      sql.NullString
	StudentNumber string
	PcNumber      sql.NullInt32
}

type UpdateActivityEndTimeRow struct {
	ID            uuid.UUID
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
}

func (q *Queries) UpdateActivityEndTime(ctx context.Context, arg UpdateActivityEndTimeParams) (UpdateActivityEndTimeRow, error) {
	row := q.db.QueryRowContext(ctx, updateActivityEndTime,
		arg.EndedAt,
		arg.ExecName,
		arg.StudentNumber,
		arg.PcNumber,
	)
	var i UpdateActivityEndTimeRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.PcNumber,
		&i.Game,
		&i.StartedAt,
		&i.EndedAt,
		&i.ExecName,
	)
	return i, err
}
