// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID         uuid.UUID
	AppName    string
	KeyID      string
	HashedKey  []byte
	CreatedAt  time.Time
	LastUsedAt sql.NullTime
}

type GamerActivity struct {
	StudentNumber string
	PcNumber      sql.NullInt32
	Game          sql.NullString
	StartedAt     sql.NullTime
	EndedAt       sql.NullTime
	ExecName      sql.NullString
	ID            uuid.UUID
}

type GamerProfile struct {
	FirstName            string
	LastName             string
	StudentNumber        string
	MembershipTier       int32
	Banned               sql.NullBool
	Notes                sql.NullString
	CreatedAt            sql.NullTime
	ID                   uuid.NullUUID
	MembershipExpiryDate sql.NullTime
}
